"""Base classes and interfaces for subject-specific diagnostic adapters."""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any, Dict, Optional


@dataclass
class DiagnosticEvaluation:
    """Internal evaluation result generated by a subject diagnostic adapter."""

    is_correct: Optional[bool]
    diagnostic_status: str  # correct, misconception_detected, insufficient_evidence, retry_required, repaired
    detected_misconception: bool
    misconception_name: Optional[str] = None
    confidence: float = 1.0
    analysis_reasoning: str = ""
    is_repaired: bool = False
    next_action: str = "retry"  # retry, proceed, review_intervention


class BaseSubjectDiagnostic(ABC):
    """Abstract interface for all subject diagnostic adapters."""

    @abstractmethod
    def evaluate(
        self,
        question: Dict[str, Any],
        student_answer: str,
        student_reasoning: Optional[str] = None,
        parent_attempt: Optional[Dict[str, Any]] = None,
    ) -> DiagnosticEvaluation:
        """
        Evaluate a student attempt on a question using subject-specific diagnostic rules.

        Args:
            question: Database question record including rubric and expected answer.
            student_answer: Raw student answer string.
            student_reasoning: Optional explanation provided by the student.
            parent_attempt: Optional previous attempt if this submission is a retry.

        Returns:
            DiagnosticEvaluation: The evaluated correctness, diagnostic status, and misconception details.
        """
        pass
